name: CI/CD Anomaly Detection

on:
  push:
    branches:
      - main

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup logging environment
        run: |
          mkdir -p $HOME/logs
          echo "LOG_FILE=$HOME/logs/workflow.log" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Or mypy, pylint, etc.

      - name: Run linter
        run: |
          python -m flake8 . > "$LOG_FILE" 2>&1 || true

      - name: Simulate slow step
        run: |
          echo "::group::slow-step"
          echo "Starting slow step..." >> "$LOG_FILE"
          sleep 60
          echo "Finished slow step" >> "$LOG_FILE"
          echo "::endgroup::"

      - name: Append additional logs if needed
        run: |
          echo "=== System Info ===" >> "$LOG_FILE"
          uname -a >> "$LOG_FILE"
          echo "=== End of Logs ===" >> "$LOG_FILE"

      - name: Run anomaly detection
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker pull maulerrr/pipeguard:latest
          docker run --rm \
            -v "${HOME}/logs/workflow.log":/app/workflow.log \
            maulerrr/pipeguard:latest \
            /app/workflow.log \
            --threshold 0.05 \
            --describe
