name: SAST + Anomaly Detection

on:
  push:
    paths:
      - '**/*.py'
      - 'generate_logs.py'
      - 'train_model.py'
      - 'detect_cli.py'
      - 'openai_utils.py'
  pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep (free SAST)
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep scan
        run: semgrep --config=p/ci --json --output=sast_logs.json .

      - name: Merge Semgrep output
        run: |
            python - << 'EOF'
            import json
            import glob

            records = []
            for fn in glob.glob("sast_logs.json"):
                with open(fn, encoding="utf-8") as f:
                    records.extend(json.load(f))

            with open("all_logs.json", "w", encoding="utf-8") as f:
                json.dump(records, f, ensure_ascii=False)
            EOF

      - name: Pull anomaly-detector image
        run: docker pull YOUR_DOCKERHUB_USERNAME/cicd-anomaly:latest

      - name: Run anomaly detection
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/all_logs.json":/data/all_logs.json \
            maulerrr/pipeguard:latest \
            --input /data/all_logs.json \
            --threshold 0.05 \
            --describe
