name: CI/CD Anomaly Detection

on:
  push:
    branches:
      - main

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

    #   - name: Build & Test (project)
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt 
    #       pytest --maxfail=1 --disable-warnings -q

      - name: Dump runner log
        run: |
          cp /home/runner/work/${{ github.repository }}/_temp/_github_workflow.log workflow.log

      - name: Run anomaly detection
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker pull maulerrr/pipeguard:latest
          docker run --rm \
            -v "${{ github.workspace }}/workflow.log":/app/workflow.log \
            maulerrr/pipeguard:latest \
            /app/workflow.log \
            --threshold 0.05 \
            --describe
